version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
        interval: weekly
        day: monday
        time: "04:00"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "PrestaShop/ui-tests-maintainers"
    labels:
      - "dependencies"