version: '3'
services:
  qanightlyresults:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "mysql://myDBUser:myDBPasswd@127.0.0.1:3306/myDBName?serverVersion=myDBServer&charset=utf8mb4"
      QANB_TOKEN: "myAPIToken"
